name: Build Image
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'explicit version number'
        default: '-'
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      TAGS: blitzbeule/rainflake:stable,blitzbeule/rainflake:${{ github.event.inputs.tag }}
    steps:
    -
      name: Check tag
      if: ${{ github.event.inputs.tag == '-' }}
      run: |
        echo "blitzbeule/rainflake:stable" >> $TAGS
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      uses: docker/build-push-action@v2.5.0
      with:
        # List of extra privileged entitlement (eg. network.host,security.insecure)
        #allow: # optional
        # List of build-time variables
        #build-args: # optional
        # Builder instance
        #builder: # optional
        # List of external cache sources for buildx (eg. user/app:cache, type=local,src=path/to/dir)
        #cache-from: # optional
        # List of cache export destinations for buildx (eg. user/app:cache, type=local,dest=path/to/dir)
        #cache-to: # optional
        # Build's context is the set of files located in the specified PATH or URL
        #context: # optional
        # Path to the Dockerfile
        #file: # optional
        # List of metadata for an image
        #labels: # optional
        # Load is a shorthand for --output=type=docker
        #load: # optional, default is false
        # Set the networking mode for the RUN instructions during build
        #network: # optional
        # Do not use cache when building the image
        #no-cache: # optional, default is false
        # List of output destinations (format: type=local,dest=path)
        #outputs: # optional
        # List of target platforms for build
        #platforms: # optional
        # Always attempt to pull a newer version of the image
        #pull: # optional, default is false
        # Push is a shorthand for --output=type=registry
        push: true
        # List of secrets to expose to the build (eg. key=string, GIT_AUTH_TOKEN=mytoken)
        #secrets: # optional
        # List of secret files to expose to the build (eg. key=filename, MY_SECRET=./secret.txt)
        #secret-files: # optional
        # List of SSH agent socket or keys to expose to the build
        #ssh: # optional
        # List of tags
        tags: 
          ${{ env.TAGS }}
        # Sets the target stage to build
        #target: # optional
        # GitHub Token used to authenticate against a repository for Git context
        #github-token: # optional, default is ${{ github.token }}
